version: "3.8"

services:
  chess_pretrain:
    build:
      context: .
      dockerfile: Dockerfile.pretrain  # Explicitly specify the Dockerfile
    image: chess_pretrain  # Name of the built image
    container_name: chess_pretrain_container
    runtime: nvidia  # Ensures GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./data:/app/data  # Mounts host data directory to /app/data
      - ./models:/app/models
      - ./figures:/app/figures
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/x86_64-linux-gnu
      - N_BLOCKS=1
      - N_HEADS=8
      - N_DIM=128
      - FF_DIM=128
    command: ["python", "/app/script.py"]
    working_dir: /app