version: "3.8"

services:
  chess_pretrain:
    build:
      context: .
      dockerfile: Dockerfile.pretrain_cnn  # Explicitly specify the Dockerfile
    image: chess_pretrain  # Name of the built image
    container_name: chess_pretrain_container
    runtime: nvidia  # Ensures GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./figures:/app/figures
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/x86_64-linux-gnu
      - TF_CPP_MIN_LOG_LEVEL=2 
      - TF_GPU_ALLOCATOR=cuda_malloc_async  
      - N_FILTERS=512
      - N_BLOCKS=4
    command: ["python", "/app/script.py"] 
    working_dir: /app