version: "3.8"

services:
  chess_pretrain:
    build:
      context: .
      dockerfile: Dockerfile.pretrain  # Explicitly specify the Dockerfile
    image: chess_pretrain  # Name of the built image
    container_name: chess_pretrain_container
    runtime: nvidia  # Ensures GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # ✅ Use all available GPUs
              capabilities: [gpu]
    volumes:
      - ./data:/app/data  # Mounts host data directory to /app/data
      - ./models:/app/models
      - ./figures:/app/figures
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # ✅ Ensures all GPUs are visible
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/lib/x86_64-linux-gnu
      - TF_CPP_MIN_LOG_LEVEL=2  # ✅ Reduces TensorFlow logging noise
      - TF_GPU_ALLOCATOR=cuda_malloc_async  # ✅ Optimizes GPU memory allocation
      - N_BLOCKS=8
      - N_HEADS=8
      - N_DIM=256
      - FF_DIM=256
    command: ["python", "/app/pretrain_script.py"]  # ✅ Ensure correct script is executed
    working_dir: /app